### ISSUE TITLE
VMs not being provisioned 

### ISSUE THREAD

**Issue by franrebo84** [amtega/ansible_role_vmware_provisioner#1]
Hello! Thanks for your playbook, it looks amazing.

I'm having problems provisioning VMs with the Readme example. Nothing is done after the ** Sequential VMWare virtual machines attributes setup** task:

```
TASK [amtega.vmware_provisioner : include_tasks] *******************************************************************************************************************************************
skipping: [localhost] => changed=false
  skip_reason: Conditional result was False

TASK [amtega.vmware_provisioner : include_tasks] *******************************************************************************************************************************************
included: /home/rebfr01@ar.ports.po/.ansible/roles/amtega.vmware_provisioner/tasks/vms_attrs.yml for localhost

TASK [amtega.vmware_provisioner : include_tasks] *******************************************************************************************************************************************
included: /home/rebfr01@ar.ports.po/.ansible/roles/amtega.vmware_provisioner/tasks/vms_attrs_sequential.yml for localhost

TASK [amtega.vmware_provisioner : Sequential vmware virtual machines attributes setup] *****************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************
localhost                  : ok=21   changed=0    unreachable=0    failed=0    skipped=15   rescued=0    ignored=0
```

This is my playbook:

```
- hosts: all
  roles:
    - role: amtega.vmware_provisioner
      vmware_provisioner_deps_resolved: true
      vmware_provisioner_no_log: false
      vmware_provisioner_hostname: nope
      vmware_provisioner_username: 'nope'
      vmware_provisioner_password: 'nope'
      vmware_provisioner_validate_certs: no
      vmware_provisioner_vm_template: '/DC/vm/Templates/N4 3.8.20.1 TEMPLATE'
      vmware_provisioner_testing_vms:
        - name: "my_vm"
          annotation: Ansible provisioned vm
          folder: '/'
          hardware:
            memory_mb: 512
            num_cpus: 1
            num_cpu_cores_per_socket: 1
          datacenter: 'DC'
          cluster: 'DC-Cluster01'
          disk:
            - size_gb: 30
              type: thin
              datastore: 'DS-V01'
          wait_for_ip_address: True
          networks:
            - name: Vlan_Test
              ip: 192.168.10.11
              netmask: 255.255.255.0
```

Maybe my vms definition is wrong, would you take a look of it?

Thanks!
